// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import bson "gopkg.in/mgo.v2/bson"
import mock "github.com/stretchr/testify/mock"
import models "github.com/jenarvaezg/MagicHub/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id bson.ObjectId) (*models.Team, error) {
	ret := _m.Called(id)

	var r0 *models.Team
	if rf, ok := ret.Get(0).(func(bson.ObjectId) *models.Team); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bson.ObjectId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFiltered provides a mock function with given fields: limit, offset, search
func (_m *Repository) FindFiltered(limit int, offset int, search string) ([]*models.Team, error) {
	ret := _m.Called(limit, offset, search)

	var r0 []*models.Team
	if rf, ok := ret.Get(0).(func(int, int, string) []*models.Team); ok {
		r0 = rf(limit, offset, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(limit, offset, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0
func (_m *Repository) Store(_a0 *models.Team) (bson.ObjectId, error) {
	ret := _m.Called(_a0)

	var r0 bson.ObjectId
	if rf, ok := ret.Get(0).(func(*models.Team) bson.ObjectId); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bson.ObjectId)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Team) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
