// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import team "github.com/jenarvaezg/MagicHub/team"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateTeam provides a mock function with given fields: name, image, description
func (_m *Service) CreateTeam(name string, image string, description string) (*team.Team, error) {
	ret := _m.Called(name, image, description)

	var r0 *team.Team
	if rf, ok := ret.Get(0).(func(string, string, string) *team.Team); ok {
		r0 = rf(name, image, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(name, image, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFiltered provides a mock function with given fields: limit, offset, search
func (_m *Service) FindFiltered(limit int, offset int, search string) ([]*team.Team, error) {
	ret := _m.Called(limit, offset, search)

	var r0 []*team.Team
	if rf, ok := ret.Get(0).(func(int, int, string) []*team.Team); ok {
		r0 = rf(limit, offset, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(limit, offset, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRouteNameFromName provides a mock function with given fields: _a0
func (_m *Service) GetRouteNameFromName(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
