#!/bin/bash

go test -covermode=count -coverprofile=coverage.out -coverpkg=./...  ./...
grep -v mocks < coverage.out > coverage_clean.out
goveralls -coverprofile=coverage_clean.out -service travis-ci -package github.com/jenarvaezg/MagicHub/...