// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import interfaces "github.com/jenarvaezg/MagicHub/interfaces"
import mock "github.com/stretchr/testify/mock"
import models "github.com/jenarvaezg/MagicHub/models"

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GetAuthTokenByProvider provides a mock function with given fields: token, provider
func (_m *AuthService) GetAuthTokenByProvider(token string, provider string) (*models.Token, error) {
	ret := _m.Called(token, provider)

	var r0 *models.Token
	if rf, ok := ret.Get(0).(func(string, string) *models.Token); ok {
		r0 = rf(token, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(token, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnAllServicesRegistered provides a mock function with given fields: r
func (_m *AuthService) OnAllServicesRegistered(r interfaces.Registry) {
	_m.Called(r)
}
