// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import interfaces "github.com/jenarvaezg/MagicHub/interfaces"
import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// OnAllControllersRegistered provides a mock function with given fields: r
func (_m *Controller) OnAllControllersRegistered(r interfaces.Registry) {
	_m.Called(r)
}
