// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import interfaces "github.com/jenarvaezg/MagicHub/interfaces"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// OnAllServicesRegistered provides a mock function with given fields: r
func (_m *Service) OnAllServicesRegistered(r interfaces.Registry) {
	_m.Called(r)
}
